$(function () {
    $.getJSON("/web_project/js/project.json", function (data) {
        console.log(data);
        var morning1 = (data["Missionary Schedule"].Mornings);
        var morning2 = (data["Missionary Schedule"].Breakfast);
        var day1 = (data["Missionary Schedule"]['Personal Study']);
        var day2 = (data["Missionary Schedule"]['Companion Study']);
        var day3 = (data["Missionary Schedule"]['Begin Proselyting']);
        var day4 = (data["Missionary Schedule"]['Lunch and Dinner']);
        var night1 = (data["Missionary Schedule"]['End of the day']);
        var night2 = (data["Missionary Schedule"].Rest);
        var time = (data["Missionary Schedule"].Schedule);
        var activity = (data["Missionary Schedule"].Activity);
        var heading1 = (data["Missionary Schedule"].Heading1);
        var heading2 = (data["Missionary Schedule"].Heading2);
        var heading3 = (data["Missionary Schedule"].Heading3);
        var heading4 = (data["Missionary Schedule"].Heading4);
        var heading5 = (data["Missionary Schedule"].Heading5);
        var heading6 = (data["Missionary Schedule"].Heading6);
        var heading7 = (data["Missionary Schedule"].Heading7);
        var heading8 = (data["Missionary Schedule"].Heading8);
        var time1 = (data["Missionary Schedule"].Schedule[0]);
        var time2 = (data["Missionary Schedule"].Schedule[1]);
        var time3 = (data["Missionary Schedule"].Schedule[2]);
        var time4 = (data["Missionary Schedule"].Schedule[3]);
        var time5 = (data["Missionary Schedule"].Schedule[4]);
        var time6 = (data["Missionary Schedule"].Schedule[5]);
        var time7 = (data["Missionary Schedule"].Schedule[6]);
        var time8 = (data["Missionary Schedule"].Schedule[7]);
        var morning1 = (data["Mission Life"].Mornings);
        var morning2 = (data["Mission Life"].Breakfast);
        var day1 = (data["Mission Life"]['Personal Study']);
        var day2 = (data["Mission Life"]['Companion Study']);
        var day3 = (data["Mission Life"]['Begin Proselyting']);
        var day4 = (data["Mission Life"]['Lunch and Dinner']);
        var night1 = (data["Mission Life"]['End of the day']);
        var night2 = (data["Mission Life"].Rest);
        var time = (data["Mission Life"].Time);
        var activity = (data["Mission Life"]["Activity Title"]);
        var heading1 = (data["Mission Life"].Heading1);
        var heading2 = (data["Mission Life"].Heading2);
        var heading3 = (data["Mission Life"].Heading3);
        var heading4 = (data["Mission Life"].Heading4);
        var heading5 = (data["Mission Life"].Heading5);
        var heading6 = (data["Mission Life"].Heading6);
        var heading7 = (data["Mission Life"].Heading7);
        var heading8 = (data["Mission Life"].Heading8);
        var time1 = (data["Mission Life"].Schedule[0]);
        var time2 = (data["Mission Life"].Schedule[1]);
        var time3 = (data["Mission Life"].Schedule[2]);
        var time4 = (data["Mission Life"].Schedule[3]);
        var time5 = (data["Mission Life"].Schedule[4]);
        var time6 = (data["Mission Life"].Schedule[5]);
        var time7 = (data["Mission Life"].Schedule[6]);
        var time8 = (data["Mission Life"].Schedule[7]);
        $('.morning1').text(morning1);
        $('.morning2').text(morning2);
        $('.day1').text(day1);
        $('.day2').text(day2);
        $('.day3').text(day3);
        $('.day4').text(day4);
        $('.night1').text(night1);
        $('.night2').text(night2);
        $('.time').text(time);
        $('.activity').text(activity);
        $('.heading1').text(heading1);
        $('.heading2').text(heading2);
        $('.heading3').text(heading3);
        $('.heading4').text(heading4);
        $('.heading5').text(heading5);
        $('.heading6').text(heading6);
        $('.heading7').text(heading7);
        $('.heading8').text(heading8);
        $('.time1').text(time1);
        $('.time2').text(time2);
        $('.time3').text(time3);
        $('.time4').text(time4);
        $('.time5').text(time5);
        $('.time6').text(time6);
        $('.time7').text(time7);
        $('.time8').text(time8);
    })
})